---
components:
  - name: sht4x
    description: |
      Driver for Sensirion SHT4x digital temperature and humidity sensor
    group: temperature
    groups:
      - name: humidity
    code_owners: UncleRus
    depends:
      - i2cdev
      - log
      - esp_idf_lib_helpers
    thread_safe: yes
    targets:
      - name: esp32
      - name: esp8266
    licenses:
      - name: BSD-3-Clause
    copyrights:
      - author:
          name: UncleRus
        year: 2021
